=== lmarent/AuctionManager/etc/auctionfile.dtd
<?xml version ="1.0" encoding="UTF-8"?>
<!-- The Document Type Definition (DTD) for the file -->

<!ELEMENT AUCTIONSET (GLOBAL, AUCTION*)>
<!ATTLIST AUCTIONSET
          ID CDATA #REQUIRED>

<!ELEMENT GLOBAL (ACTION|PREF)*>
<!-- global configuration is overruled by per auction configuration -->
          
<!ELEMENT AUCTION (ACTION, FIELD*)>
<!ATTLIST AUCTION
        ID CDATA #REQUIRED>

<!ELEMENT ACTION (PREF*)>
<!ATTLIST ACTION
        NAME CDATA #REQUIRED
        DEFAULT CDATA #REQUIRED >
        
<!ELEMENT PREF (#PCDATA)>
<!ATTLIST PREF
        NAME CDATA #REQUIRED
        TYPE (UInt8|SInt8|UInt16|SInt16|UInt32|SInt32|UInt64|SInt64|Bool|Binary|String|Float32|Float64) "String">
                
<!ELEMENT FIELD (#PCDATA)>
<!ATTLIST FIELD
        BID_TEMPL CDATA #IMPLIED
        BID_OPT_TEMPL CDATA #IMPLIED
        ALLOC_TEMPL CDATA #IMPLIED>

=== lmarent/AuctionManager/etc/example_auctions2.xml
<?xml version ="1.0" encoding="UTF-8"?>
<!DOCTYPE AUCTIONSET SYSTEM "auctionfile.dtd"> 
<AUCTIONSET ID="General">
  <!-- global part is the default for all auctions -->
  <!-- overwritten by rule specific configuration -->
  <GLOBAL>
    <!-- how long the auctions are active - value in seconds-->
    <PREF NAME="Duration">100000</PREF>

    <!-- How often they should be run - value in seconds -->
    <PREF NAME="Interval">10</PREF>
  </GLOBAL>
  <AUCTION ID="1">
    <ACTION NAME="bas" DEFAULT="true">
    <PREF NAME="Bandwidth" TYPE="Float64">8</PREF>
    <PREF NAME="ReservePrice" TYPE="Float64">0.012</PREF>    
    </ACTION>
  </AUCTION>
</AUCTIONSET>

=== lmarent/AuctionManager/etc/example_auctions1.xml
<?xml version ="1.0" encoding="UTF-8"?>
<!DOCTYPE AUCTIONSET SYSTEM "auctionfile.dtd"> 
<AUCTIONSET ID="General">
  <!-- global part is the default for all auctions -->
  <!-- overwritten by rule specific configuration -->
  <GLOBAL>
    <!-- how long the auctions are active - value in seconds-->
    <PREF NAME="Duration">100000</PREF>

    <!-- How often they should be run - value in seconds -->
    <PREF NAME="Interval">10</PREF>
  </GLOBAL>
  <AUCTION ID="1">
    <ACTION NAME="bas" DEFAULT="true"></ACTION>
	<FIELD BID_TEMPL="yes" BID_OPT_TEMPL="no" ALLOC_TEMPL="yes">quantity</FIELD>
	<FIELD BID_TEMPL="yes" BID_OPT_TEMPL="no">unitbudget</FIELD>
	<FIELD BID_TEMPL="yes" BID_OPT_TEMPL="no" ALLOC_TEMPL="yes">unitprice</FIELD>
	<FIELD BID_TEMPL="no" BID_OPT_TEMPL="yes" ALLOC_TEMPL="no">bidingduration</FIELD>
  </AUCTION>
</AUCTIONSET>
