=== lmarent/AuctionManager/etc/fielddef.dtd
<?xml version ="1.0" encoding="UTF-8"?>
<!-- The Document Type Definition (DTD) for the file -->

<!ELEMENT FIELDDEF (DEF)*>
<!ELEMENT DEF (#PCDATA)>
<!ATTLIST DEF
LENGTH CDATA "1" 
TYPE (UInt8|SInt8|UInt16|SInt16|UInt32|SInt32|UInt64|SInt64|Bool|Binary|String|Float|Double) #REQUIRED 
>

=== lmarent/AuctionManager/etc/fielddef_standard.xml
<?xml version ="1.0" encoding="UTF-8"?>
<!DOCTYPE FIELDDEF SYSTEM "fielddef.dtd">
<FIELDDEF>
  
  <!-- Reserved for price -->
  <DEF LENGTH="8" TYPE="Float" >MaxUnitValuation</DEF>
  <DEF LENGTH="8" TYPE="Float" >UnitValue</DEF>
  <DEF LENGTH="8" TYPE="Float" >UnitBudget</DEF>
  <DEF LENGTH="8" TYPE="Float" >TotalBudget</DEF>
  <!-- General fields -->

  <DEF LENGTH="4" TYPE="UInt32" >AuctioningTimeSeconds</DEF>
  <DEF LENGTH="8" TYPE="UInt64" >AuctioningTimeMilliSeconds</DEF>
  <DEF LENGTH="8" TYPE="UInt64" >AuctioningTimeMicroSeconds</DEF>
  <DEF LENGTH="8" TYPE="UInt64" >AuctioningTimeNanoSeconds</DEF>
  <DEF LENGTH="4" TYPE="UInt16" >AuctioningAlgorithmCode</DEF>
  <DEF LENGTH="4" TYPE="IPAddr" >SourceIpv4Address</DEF>
  <DEF LENGTH="1" TYPE="UInt8" >SourceIpv4PrefixLenght</DEF>
  <DEF LENGTH="4" TYPE="IPAddr" >DestinationIpv4Address</DEF>
  <DEF LENGTH="1" TYPE="UInt8" >DestinationIpv4PrefixLen</DEF>
  <DEF LENGTH="16" TYPE="IP6Addr" >SourceIpv6Address</DEF>
  <DEF LENGTH="16" TYPE="IP6Addr" >DestinationIpv6Address</DEF>
  <DEF LENGTH="1" TYPE="UInt8" >SourceIpv6PrefixLenght</DEF>
  <DEF LENGTH="1" TYPE="UInt8" >DestinationIpv6PrefixLenght</DEF>
  <DEF LENGTH="65535" TYPE="Binary" >PaddingOctects</DEF>
  <DEF LENGTH="65535" TYPE="Binary" >IpHeaderPacketSection</DEF>
  <DEF LENGTH="65535" TYPE="Binary" >IpPayloadPacketSection</DEF>
  <DEF LENGTH="65535" TYPE="Binary" >DataLinkFrameSection</DEF>
  <DEF LENGTH="6" TYPE="Binary" >SourceMacAddress</DEF>
  <DEF LENGTH="6" TYPE="Binary" >PostDestinationMacAddress</DEF>
  
  <!-- Fields for identifiers-->
  <DEF LENGTH="128" TYPE="String" >IdAuction</DEF>
  <DEF LENGTH="128" TYPE="String" >IdBid</DEF>
  <DEF LENGTH="128" TYPE="String" >IdAllocation</DEF>
  <DEF LENGTH="128" TYPE="String" >IdRecord</DEF>

  <!-- Fields for intervals -->
  <DEF LENGTH="4" TYPE="UInt32" >StartSeconds</DEF>
  <DEF LENGTH="4" TYPE="UInt32" >EndSeconds</DEF>
  <DEF LENGTH="8" TYPE="UInt64" >StartMilliSeconds</DEF>
  <DEF LENGTH="8" TYPE="UInt64" >EndMilliSeconds</DEF>
  <DEF LENGTH="128" TYPE="String" >AuctioningAlgorithName</DEF>

  <!-- Fields for quantities -->
  <DEF LENGTH="8" TYPE="Float" >Quantity</DEF>
</FIELDDEF>

=== lmarent/AuctionManager/etc/fielddef.xml
<?xml version ="1.0" encoding="UTF-8"?>
<!DOCTYPE FIELDDEF SYSTEM "fielddef.dtd">
<FIELDDEF>
  <!-- General fields -->
  <DEF LENGTH="8" TYPE="Double" ENO="0" FTYPE="33">Quantity</DEF>
  <DEF LENGTH="8" TYPE="Double" ENO="0" FTYPE="2">UnitPrice</DEF>
  <DEF LENGTH="8" TYPE="Double" ENO="0" FTYPE="3">UnitBudget</DEF>
  <DEF LENGTH="8" TYPE="Double" ENO="0" FTYPE="1">MaxValue</DEF>
  <DEF LENGTH="4" TYPE="SInt32" ENO="0" FTYPE="5">Duration</DEF>
  <DEF LENGTH="4" TYPE="Float" ENO="0" FTYPE="38">Bandwidth</DEF>
  <!-- Reserve price -->
  <DEF LENGTH="8" TYPE="Double" ENO="0" FTYPE="39">ReservePrice</DEF>
  
</FIELDDEF>
