=== lmarent/AuctionManager/etc/netagnt.conf.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- The Document Type Definition (DTD) for the file -->

        <!ELEMENT CONFIG (MAIN ,  CONTROL, AGENT_PROCESSOR )>
        <!ELEMENT MAIN (PREF*)>
        <!ELEMENT CONTROL (PREF* , ACCESS)>
        <!ELEMENT ACCESS (ALLOW | DENY)*>
        <!ELEMENT ALLOW (#PCDATA)>
        <!ELEMENT DENY (#PCDATA)>
        <!ELEMENT AGENT_PROCESSOR (PREF*)>
        <!ELEMENT PREF (#PCDATA)>

        <!ATTLIST ALLOW
                TYPE (Host | User | Group) "Host"
        >
        <!ATTLIST DENY
                TYPE (Host | User | Group) "Host"
        >
        <!ATTLIST PREF
                NAME CDATA #REQUIRED
                TYPE (UInt8 | SInt8 | UInt16 | SInt16 | UInt32 | SInt32 | UInt64 | SInt64 | Float32 |
            Float64 | Bool | String | IPAddr ) "String"
   >

=== lmarent/AuctionManager/etc/netagnt.conf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CONFIG SYSTEM "netagnt.conf.dtd"> 
<CONFIG>
  <MAIN>
    <!-- verbose level for logging -->
    <PREF NAME="VerboseLevel" TYPE="UInt8">4</PREF>
    <!-- log file name -->
    <PREF NAME="LogFile">/home/luis/AuctionManager/etc/log/netagent.log</PREF>
    <!-- pid file location -->
    <PREF NAME="PidFile">/tmp/netagent.pid</PREF>
    <!-- ansl-client configuration file -->    
    <PREF NAME="AnslpConfFile">/home/luis/AuctionManager/etc/nsis-ka_agent.conf</PREF>
    <!-- filter attribute definition file -->    
    <PREF NAME="FilterDefFile">/home/luis/AuctionManager/etc/fielddef.xml</PREF>
    <!-- filter constant file -->
    <PREF NAME="FilterConstFile">/home/luis/AuctionManager/etc/fieldval.xml</PREF>     
    <!-- auction file to load at start -->
    <PREF NAME="ResourceRequestFile">/home/luis/AuctionManager/etc/example_resource_request1.xml</PREF>
  </MAIN>
  <CONTROL>
    <!-- enable remote control interface -->
    <PREF NAME="Enable" TYPE="Bool">yes</PREF>
    <!-- port for control connections -->
    <PREF NAME="ControlPort" TYPE="UInt16">12248</PREF>
    <!-- use SSL encryption -->
    <PREF NAME="UseSSL" TYPE="Bool">no</PREF>
    <!-- use IPv6 (if no IPv6 interface present IP4 will be used) -->
    <PREF NAME="UseIPv6" TYPE="Bool">no</PREF>
    <!-- log all incoming control requests -->
    <PREF NAME="LogOnConnect" TYPE="Bool">yes</PREF>
    <!-- log all agent commands -->
    <PREF NAME="LogCommand" TYPE="Bool">yes</PREF>
    <!-- access list -->
    <ACCESS>
      <ALLOW TYPE="Host">All</ALLOW>
      <ALLOW TYPE="User">admin:admin</ALLOW>
      <DENY>All</DENY>
    </ACCESS>
  </CONTROL>
  <AGENT_PROCESSOR>
    <!-- run as separate thread -->
    <PREF NAME="Thread" TYPE="Bool">no</PREF>
    <!-- Auctioner server data-->
    <PREF NAME="AuctionerServer" TYPE="IPAddr">no</PREF>
    <PREF NAME="Auctionerport" TYPE="UInt16">no</PREF>
    <PREF NAME="User" TYPE="String">no</PREF>
    <PREF NAME="Password" TYPE="String">no</PREF>
    <!-- Agent Parameters-->
    
  </AGENT_PROCESSOR>  
</CONFIG>
